### ISSUE TITLE
reconciler is nil

### ISSUE THREAD

**Issue by okilimnik** [amorokh/om-navigate#3]
Navigators don't pass reconciler to children, so this code:

`(om/transact! this '[(set-field {:field :show-spinner?
                                                              :value true})])`

returns an error:

`#object[TypeError TypeError: null is not an object (evaluating 'new cljs.core.Keyword(null,"history","history",-247395220).cljs$core$IFn$_invoke$arity$1(cfg).add')]`

**Comment by amorokh** [comment]
Yes, I am aware of this problem, current implementation is a rather naive attempt and not really useful. I am working on it though..

**Comment by okilimnik** [comment]
Thanks for the answer. Finally I switched to reagent. Such things are much easier there

**Comment by amorokh** [comment]
Ok, I have no experience with reagent, but from what I understand om and reagent are really different. Anyway, merged a fix for this issue..
